# Generated by Django 2.1 on 2018-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_loc', '0002_product_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
